# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u63a5\u53e3\u7f16\u53f7')),
                ('aid', models.IntegerField(default=0, verbose_name='\u63a5\u53e3\u5206\u7c7bid')),
                ('num', models.CharField(max_length=100, null=True, verbose_name='\u63a5\u53e3\u7f16\u53f7')),
                ('url', models.CharField(max_length=240, null=True, verbose_name='\u8bf7\u6c42\u5730\u5740')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='\u63a5\u53e3\u540d')),
                ('des', models.CharField(max_length=300, null=True, verbose_name='\u63a5\u53e3\u63cf\u8ff0')),
                ('parameter', models.TextField(verbose_name='\u8bf7\u6c42\u53c2\u6570{\u6240\u6709\u7684\u4e3b\u6c42\u53c2\u6570,\u4ee5json\u683c\u5f0f\u5728\u6b64\u5b58\u653e}')),
                ('memo', models.TextField(verbose_name='\u5907\u6ce8')),
                ('re', models.TextField(verbose_name='\u8fd4\u56de\u503c')),
                ('lasttime', models.IntegerField(null=True, verbose_name='\u63d0\u540e\u64cd\u4f5c\u65f6\u95f4')),
                ('lastuid', models.IntegerField(null=True, verbose_name='\u6700\u540e\u4fee\u6539uid')),
                ('isdel', models.IntegerField(default=0, verbose_name='{0:\u6b63\u5e38,1:\u5220\u9664}')),
                ('type', models.CharField(max_length=11, null=True, verbose_name='\u8bf7\u6c42\u65b9\u5f0f')),
                ('ord', models.IntegerField(default=0, verbose_name='\u6392\u5e8f(\u503c\u8d8a\u5927,\u8d8a\u9760\u524d)')),
            ],
            options={
                'db_table': 'api',
                'verbose_name': '\u63a5\u53e3\u660e\u7ec6\u8868',
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5206\u7c7bid')),
                ('cname', models.CharField(max_length=200, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('cdesc', models.CharField(max_length=200, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
                ('isdel', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664{0:\u6b63\u5e38,1\u5220\u9664}')),
                ('addtime', models.IntegerField(default=0, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'cate',
                'verbose_name': '\u63a5\u53e3\u5206\u7c7b\u8868',
            },
        ),
    ]
