# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='firstuid',
            field=models.IntegerField(null=True, verbose_name='\u9996\u6b21\u589e\u52a0uid'),
        ),
    ]
